import type {
  Goal,
  Task,
  Artifact,
  Memory,
  AgentRun,
  Approval,
} from "./types";

export const goals: Goal[] = [
  {
    id: "g_1",
    title: "Build the system that helps build this system",
    description:
      "Private v0 of Founder Cockpit that dogfoods its own construction.",
    why_it_matters:
      "We need a working loop before we can compound. The cockpit must be useful to its first user — me — within a week.",
    success_metric: "I use it daily for 7 consecutive days",
    status: "active",
    deadline: "2026-06-10",
    active: true,
    created_at: "2026-05-20T09:00:00Z",
  },
  {
    id: "g_2",
    title: "Agent can create useful GitHub-ready tasks",
    description: "Daily Operator produces tasks small enough to ship.",
    why_it_matters:
      "If tasks aren't shippable, the loop breaks. GitHub is the execution layer.",
    success_metric: "5 tasks created, 2 implemented end-to-end",
    status: "active",
    deadline: "2026-06-20",
    active: false,
    created_at: "2026-05-21T09:00:00Z",
  },
  {
    id: "g_3",
    title: "App compounds project memory",
    description:
      "Decisions, artifacts, and agent notes are saved and reused across runs.",
    why_it_matters:
      "Memory is the moat. Without it the agent starts from zero every morning.",
    success_metric: "Last 20 memories visibly influence the next daily brief",
    status: "active",
    deadline: "2026-07-01",
    active: false,
    created_at: "2026-05-22T09:00:00Z",
  },
];

export const tasks: Task[] = [
  {
    id: "t_1",
    goal_id: "g_1",
    title: "Create the first database schema",
    description: "Goals, tasks, artifacts, memories, agent_runs, approvals.",
    status: "approved",
    priority: 1,
    risk_level: "low",
    output_type: "sql_migration",
    created_at: "2026-05-25T09:00:00Z",
  },
  {
    id: "t_2",
    goal_id: "g_1",
    title: "Static cockpit UI",
    description: "Hardcoded data, 5 sections, make it feel right.",
    status: "in_progress",
    priority: 1,
    risk_level: "low",
    output_type: "ui",
    created_at: "2026-05-26T09:00:00Z",
  },
  {
    id: "t_3",
    goal_id: "g_1",
    title: "Wire Supabase + replace fixtures",
    description: "Mechanical swap from in-file fixtures to Supabase reads.",
    status: "suggested",
    priority: 2,
    risk_level: "medium",
    output_type: "code",
    created_at: "2026-05-26T10:00:00Z",
  },
  {
    id: "t_4",
    goal_id: "g_2",
    title: "Daily Operator: brief generator",
    description: "Reads goals + memories + recent artifacts, emits a brief.",
    status: "suggested",
    priority: 1,
    risk_level: "medium",
    output_type: "agent",
    created_at: "2026-05-26T11:00:00Z",
  },
  {
    id: "t_5",
    goal_id: "g_2",
    title: "Add GitHub issue creation",
    description: "Push approved tasks as GitHub issues with full context.",
    status: "suggested",
    priority: 1,
    risk_level: "low",
    output_type: "integration",
    created_at: "2026-05-26T12:00:00Z",
  },
  {
    id: "t_6",
    goal_id: "g_1",
    title: "Task approval flow",
    description: "Approve / Reject / Revise buttons persist + audit log.",
    status: "needs_review",
    priority: 2,
    risk_level: "low",
    output_type: "ui",
    created_at: "2026-05-25T15:00:00Z",
  },
  {
    id: "t_7",
    goal_id: "g_3",
    title: "Memory page (read-only)",
    description: "Browse all memories grouped by type.",
    status: "approved",
    priority: 2,
    risk_level: "low",
    output_type: "ui",
    created_at: "2026-05-25T16:00:00Z",
  },
  {
    id: "t_8",
    goal_id: "g_3",
    title: "Write onboarding doc for the agent",
    description: "System prompt + guardrails for Daily Operator.",
    status: "suggested",
    priority: 3,
    risk_level: "low",
    output_type: "doc",
    created_at: "2026-05-26T13:00:00Z",
  },
  {
    id: "t_9",
    goal_id: "g_1",
    title: "Decision memo: private-first vs marketing-first",
    description: "Document the call and reasoning.",
    status: "done",
    priority: 2,
    risk_level: "low",
    output_type: "decision_memo",
    created_at: "2026-05-24T10:00:00Z",
  },
  {
    id: "t_10",
    goal_id: "g_2",
    title: "Critique homepage layout",
    description: "Design critique pass on current cockpit.",
    status: "done",
    priority: 3,
    risk_level: "low",
    output_type: "design_critique",
    created_at: "2026-05-24T14:00:00Z",
  },
  {
    id: "t_11",
    goal_id: "g_1",
    title: "Auto-deploy via Vercel",
    description: "Hook up preview deploys.",
    status: "rejected",
    priority: 3,
    risk_level: "medium",
    output_type: "infra",
    created_at: "2026-05-23T10:00:00Z",
  },
  {
    id: "t_12",
    goal_id: "g_3",
    title: "Vector embeddings for memory",
    description: "Later — keep it simple for v0.",
    status: "rejected",
    priority: 4,
    risk_level: "high",
    output_type: "infra",
    created_at: "2026-05-23T11:00:00Z",
  },
];

export const artifacts: Artifact[] = [
  {
    id: "a_1",
    goal_id: "g_1",
    task_id: null,
    type: "daily_brief",
    title: "Daily Brief — May 27",
    content:
      "The cockpit shell renders. Goals seeded. Next: ship the static UI so the loop is visible end-to-end.",
    url: null,
    created_by_agent: "daily_operator",
    created_at: "2026-05-27T08:00:00Z",
  },
  {
    id: "a_2",
    goal_id: "g_1",
    task_id: "t_1",
    type: "prd",
    title: "Product spec: Founder Cockpit v0",
    content:
      "Five sections. One loop. The first goal is the meta-goal. Memory is read-only at first.",
    url: null,
    created_by_agent: "spec_writer",
    created_at: "2026-05-25T11:00:00Z",
  },
  {
    id: "a_3",
    goal_id: "g_2",
    task_id: "t_5",
    type: "github_issue",
    title: "Draft: github-issue creator for approved tasks",
    content:
      "Implements POST /api/github/issues. Body = task description + acceptance criteria + goal context.",
    url: "https://github.com/example/repo/issues/42",
    created_by_agent: "issue_drafter",
    created_at: "2026-05-26T15:00:00Z",
  },
  {
    id: "a_4",
    goal_id: "g_2",
    task_id: "t_10",
    type: "design_critique",
    title: "Homepage critique",
    content:
      "Too much chrome. Sidebar competes with content. Move to centered single column.",
    url: null,
    created_by_agent: "design_reviewer",
    created_at: "2026-05-24T16:00:00Z",
  },
  {
    id: "a_5",
    goal_id: "g_1",
    task_id: "t_9",
    type: "decision_memo",
    title: "Private-first, not marketing-first",
    content:
      "We dogfood before we position. Public surface waits until the loop is real.",
    url: null,
    created_by_agent: "founder",
    created_at: "2026-05-24T12:00:00Z",
  },
  {
    id: "a_6",
    goal_id: "g_3",
    task_id: null,
    type: "research_note",
    title: "How Linear handles memory in their AI features",
    content:
      "They keep state close to the object (issue/project) rather than a global vector store. Worth copying.",
    url: null,
    created_by_agent: "researcher",
    created_at: "2026-05-23T17:00:00Z",
  },
  {
    id: "a_7",
    goal_id: "g_1",
    task_id: "t_2",
    type: "task_plan",
    title: "Static cockpit — execution plan",
    content:
      "Routes, fixtures, components. No DB. Ship by EOD.",
    url: null,
    created_by_agent: "planner",
    created_at: "2026-05-27T09:30:00Z",
  },
  {
    id: "a_8",
    goal_id: "g_2",
    task_id: null,
    type: "growth_draft",
    title: "Tweet draft: 'I'm building a cockpit for solo founders'",
    content:
      "Held for later — private-first decision means no public surface yet.",
    url: null,
    created_by_agent: "growth",
    created_at: "2026-05-26T18:00:00Z",
  },
];

export const memories: Memory[] = [
  {
    id: "m_1",
    type: "company",
    title: "What we're building",
    content:
      "A founder cockpit for solo founders. The product must help build itself.",
    importance: 3,
    created_at: "2026-05-20T09:00:00Z",
  },
  {
    id: "m_2",
    type: "company",
    title: "First user",
    content: "PK. Single-tenant for now.",
    importance: 3,
    created_at: "2026-05-20T09:05:00Z",
  },
  {
    id: "m_3",
    type: "company",
    title: "The core loop",
    content:
      "brief → task → artifact → approval → memory. Every screen serves this loop.",
    importance: 3,
    created_at: "2026-05-20T09:10:00Z",
  },
  {
    id: "m_4",
    type: "company",
    title: "Execution layer",
    content: "GitHub is the execution layer. Tasks become issues.",
    importance: 2,
    created_at: "2026-05-20T09:15:00Z",
  },
  {
    id: "m_5",
    type: "company",
    title: "First agent",
    content: "Daily Operator. Reads memory + goals, emits a daily brief.",
    importance: 2,
    created_at: "2026-05-20T09:20:00Z",
  },
  {
    id: "m_6",
    type: "company",
    title: "Visual direction",
    content:
      "Minimal, whitespace-heavy, single column. Quiet typography. Pink alpha pill.",
    importance: 2,
    created_at: "2026-05-27T10:00:00Z",
  },
  {
    id: "m_7",
    type: "decision",
    title: "Private-first, not marketing-first",
    content:
      "Dogfood before positioning. May 27, 2026. Holds until loop is real for 7 days.",
    importance: 3,
    created_at: "2026-05-24T12:00:00Z",
  },
  {
    id: "m_8",
    type: "decision",
    title: "Skip vector memory for v0",
    content:
      "Last 20–50 memories read flat. Add embeddings only when retrieval breaks.",
    importance: 2,
    created_at: "2026-05-23T11:00:00Z",
  },
  {
    id: "m_9",
    type: "decision",
    title: "Output-first, not chat-first",
    content: "Artifacts are the product. Chat is scaffolding.",
    importance: 3,
    created_at: "2026-05-22T15:00:00Z",
  },
  {
    id: "m_10",
    type: "decision",
    title: "Supabase for v0 storage",
    content: "Six tables. No fancy ORM. Mechanical to swap later.",
    importance: 1,
    created_at: "2026-05-22T16:00:00Z",
  },
  {
    id: "m_11",
    type: "decision",
    title: "Top-nav, not sidebar",
    content: "Sidebar competed with the content. Single centered column wins.",
    importance: 2,
    created_at: "2026-05-27T10:30:00Z",
  },
  {
    id: "m_12",
    type: "decision",
    title: "Defer auth + multi-user",
    content: "Single user only until the loop is dogfooded for a week.",
    importance: 1,
    created_at: "2026-05-21T10:00:00Z",
  },
  {
    id: "m_13",
    type: "agent_note",
    title: "Builder Agent — task size",
    content: "Prefer small implementation tasks. Aim for <2 hours each.",
    importance: 2,
    created_at: "2026-05-23T14:00:00Z",
  },
  {
    id: "m_14",
    type: "agent_note",
    title: "Builder Agent — guardrails",
    content:
      "Never touch auth, billing, or db migrations without explicit approval.",
    importance: 3,
    created_at: "2026-05-23T14:05:00Z",
  },
  {
    id: "m_15",
    type: "agent_note",
    title: "Builder Agent — issue-first",
    content:
      "Create GitHub-ready issues before writing code. The issue is the contract.",
    importance: 2,
    created_at: "2026-05-23T14:10:00Z",
  },
  {
    id: "m_16",
    type: "agent_note",
    title: "Daily Operator — brevity",
    content: "Daily briefs ≤ 6 bullets. If it doesn't fit, prioritize harder.",
    importance: 2,
    created_at: "2026-05-25T08:00:00Z",
  },
  {
    id: "m_17",
    type: "agent_note",
    title: "Design Reviewer — taste",
    content: "Borrow from Linear, Vercel, Stripe. Avoid gradient slop.",
    importance: 1,
    created_at: "2026-05-24T16:00:00Z",
  },
  {
    id: "m_18",
    type: "agent_note",
    title: "Researcher — citations",
    content: "Always link sources. No vibes-based research notes.",
    importance: 1,
    created_at: "2026-05-23T17:00:00Z",
  },
];

export const agentRuns: AgentRun[] = [
  {
    id: "r_1",
    agent_type: "daily_operator",
    status: "succeeded",
    input: "morning run",
    output: "Daily brief emitted (a_1)",
    error: null,
    created_at: "2026-05-27T08:00:00Z",
  },
  {
    id: "r_2",
    agent_type: "issue_drafter",
    status: "succeeded",
    input: "draft issue for t_5",
    output: "Issue draft a_3",
    error: null,
    created_at: "2026-05-26T15:00:00Z",
  },
  {
    id: "r_3",
    agent_type: "planner",
    status: "running",
    input: "plan static cockpit",
    output: null,
    error: null,
    created_at: "2026-05-27T09:30:00Z",
  },
];

export const approvals: Approval[] = [
  {
    id: "ap_1",
    task_id: "t_5",
    artifact_id: null,
    action: "Create GitHub issue for task schema",
    status: "pending",
    notes: "",
    created_at: "2026-05-27T09:00:00Z",
  },
  {
    id: "ap_2",
    task_id: null,
    artifact_id: "a_2",
    action: "Update product positioning doc",
    status: "pending",
    notes: "",
    created_at: "2026-05-27T09:10:00Z",
  },
  {
    id: "ap_3",
    task_id: "t_2",
    artifact_id: null,
    action: "Run Builder Agent on dashboard layout",
    status: "pending",
    notes: "",
    created_at: "2026-05-27T09:15:00Z",
  },
  {
    id: "ap_4",
    task_id: "t_6",
    artifact_id: null,
    action: "Approve task approval flow",
    status: "pending",
    notes: "",
    created_at: "2026-05-27T09:20:00Z",
  },
  {
    id: "ap_5",
    task_id: "t_4",
    artifact_id: null,
    action: "Greenlight Daily Operator brief generator",
    status: "pending",
    notes: "",
    created_at: "2026-05-27T09:25:00Z",
  },
];

export const suggestedNextMoves = [
  "Add GitHub issue creation",
  "Improve task approval flow",
  "Create memory page",
  "Write onboarding doc for the agent",
];

export const dailyBrief = {
  changed: [
    "Visual direction switched to single-column minimal layout",
    "Decision memo logged: private-first",
  ],
  blocked: [
    "Supabase wiring blocked on schema sign-off",
  ],
  recommended: [
    "Ship static cockpit today",
    "Draft Daily Operator system prompt",
  ],
  needs_decision: [
    "Pick accent color — settled on pink ALPHA pill, black/white otherwise",
    "Decide if memory page is editable in v0 (recommend: read-only)",
  ],
};
